config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :members
  resources :employees
  resources :wait_statuses
  resources :registrations, except: :show
  resources :sessions, except: :index

  # Set the root url
  root :to => 'home#home', as: :home

  # Authentication
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def home
		@recent_nonadmin_posts = Post.chronological.non_admin_posts.take(5)
		@last_admin_post = Post.last_admin_post
		@registrations_almost_done = Registration.almost_done.chronological
		@birthday_members = Member.birthday_today.alphabetical
	end

end

app/views/home/_almost_done_registrations.html.erb
<div class="section">
	<h3>등록 만기 예정 회원</h3>
	<% unless @registrations_almost_done.empty? %>
		<table class="index-table">
			<thead>
				<tr>
					<th>이름</th>
					<th>좌석번호</th>
					<th>전화번호</th>
					<th>만기 날짜</th>
				</tr>
			</thead>
			<% @registrations_almost_done.each do |r| %>
				<tr>
					<td><%= link_to r.member.name, r.member %></td>
					<td><%= r.seat_number %></td>
					<td><%= r.member.phone %></td>
					<td><%= r.end_date %></td>
				</tr>
			<% end %>
		</table>
	<% else %>
		<p>5일 이내 만기 예정인 예약이 없습니다.</p>
	<% end %>
</div>

app/views/home/_birthday_members.html.erb
<div class="section">
	<h3>생일인 회원</h3>
	<% unless @birthday_members.empty? %>
		<table class="index-table">
			<thead>
				<tr>
					<th>이름</th>
					<th>전화번호</th>
					<th>이메일</th>
					<th>Status</th>
				</tr>
			</thead>
			<% @birthday_members.each do |m| %>
				<tr>
					<td><%= link_to m.name, m %></td>
					<td><%= m.phone %></td>
					<td><%= m.email %></td>
					<td>
	          <% if m.status.class.name == "Registration" %>
	            <%= "#{m.status.seat_number}번 테이블 ~#{m.status.end_date}" %>
	          <% elsif m.status.class.name == "WaitStatus" %>
	            <%= "#{m.status.table_type.capitalize} 테이블 #{m.status.start_date}부터 대기 중" %>
	          <% else %>
	            없음
	          <% end %>
	        </td>
				</tr>
			<% end %>
		</table>
	<% else %>
		<p>오늘 생일인 회원이 없습니다.</p>
	<% end %>
</div>

app/views/home/_home_features.html.erb
<div id="home-features">
	<div id="home-shortcuts">
		<%= link_to new_post_path do %>
			<%= fa_icon "pencil" %> 게시물 작성
		<% end %>
		<%= link_to new_member_path do %>
			<%= fa_icon "plus" %> 회원추가
		<% end %>
	</div>
	<% if @last_admin_post %>
		<div class="post">
			<h4><%= @last_admin_post.employee.name %></h4>
			<small>
				<%= @last_admin_post.created_at.strftime("%Y/%m/%d - %H:%M") %>
			</small>
			<pre><%= @last_admin_post.content %></pre>
			<% if can? :edit, @last_admin_post %>
				<div class="post-commands">
					<%= link_to edit_post_path(@last_admin_post) do %>
						<%= fa_icon "pencil" %>
					<% end %> |
					<%= link_to @last_admin_post, method: :delete, data: { confirm: '이 게시글을 지우시겠습니까?' } do %>
						<%= fa_icon "times" %>
					<% end %>
				</div>
			<% end %>
		</div>
	<% else %>
		<p>어드민이 올린 게시물이 없습니다.</p>
	<% end %>
</div>

app/views/home/_recent_posts.html.erb
<% @recent_nonadmin_posts.each do |p| %>
	<div class="post">
		<h4><%= p.employee.name %></h4>
		<small>
			<%= p.created_at.strftime("%Y/%m/%d - %H:%M") %>
		</small>
		<p><pre><%= p.content %></pre></p>
		<% if can? :edit, p %>
			<div class="post-commands">
				<%= link_to edit_post_path(p) do %>
					<%= fa_icon "pencil" %>
				<% end %> |
				<%= link_to p, method: :delete, data: { confirm: '이 게시글을 지우시겠습니까?' } do %>
					<%= fa_icon "times	" %>
				<% end %>
			</div>
		<% end %>
	</div>
<% end %>

app/views/home/home.html.erb
<div class="sidebar width-60">
	<%= render 'home_features' %>
	<%= render 'almost_done_registrations' %>
	<%= render 'birthday_members' %>
	<%= render 'recent_posts' %>
</div>
<div class="sidebar right-sidebar">
	<div id="start-of-shift" class="box">
		Things to do at the start of a shift
		<ul>
			<li>blah</li>
			<li>blah</li>
			<li>blah</li>
		</ul>
	</div>
	<div id="during-shift" class="box">
		Things to do during a shift
		<ul>
			<li>blah</li>
			<li>blah</li>
			<li>blah</li>
		</ul>
	</div>
	<div id="end-of-shift" class="box">
		Things to do at the end of a shift
		<ul>
			<li>blah</li>
			<li>blah</li>
			<li>blah</li>
		</ul>
	</div>
</div>