config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :members
  resources :employees
  resources :wait_statuses
  resources :registrations, except: :show
  resources :sessions, except: :index

  # Set the root url
  root :to => 'home#home', as: :home

  # Authentication
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

end

app/controllers/wait_statuses_controller.rb
class WaitStatusesController < ApplicationController
  before_action :set_wait_status, only: [:show, :edit, :update, :destroy]
  before_action :check_login
  authorize_resource

  # GET /wait_statuses
  # GET /wait_statuses.json
  def index
    @current_wait_statuses = WaitStatus.current.order('table_type', 'start_date')
    respond_to do |format|
      format.html
      format.csv { send_data @current_wait_statuses.to_csv }
    end
  end

  # GET /wait_statuses/new
  def new
    @wait_status = WaitStatus.new
    @member = Member.find(params[:member_id])
  end

  # POST /wait_statuses
  # POST /wait_statuses.json
  def create
    @wait_status = WaitStatus.new(wait_status_params)
    @wait_status.start_date = Date.today
    @wait_status.employee_id = current_user.id
    respond_to do |format|
      if @wait_status.save
        format.html { redirect_to member_path(@wait_status.member_id), notice: 'Wait status was successfully created.' }
        format.json { render :show, status: :created, location: @wait_status }
      else
        format.html { render :new }
        format.json { render json: @wait_status.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wait_status
      @wait_status = WaitStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wait_status_params
      params.require(:wait_status).permit(:table_type, :start_date, :member_id, :employee_id)
    end
end

app/helpers/wait_statuses_helper.rb
module WaitStatusesHelper
end

app/views/wait_statuses/_form.html.erb
<%= form_for(@wait_status) do |f| %>
  <% if @wait_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wait_status.errors.count, "error") %> prohibited this wait_status from being saved:</h2>

      <ul>
      <% @wait_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :table_type %><br>
    <%= f.select :table_type, collection: WaitStatus::TABLE_TYPES %>
  </div>
  <%= f.hidden_field :member_id, :value => @member.id %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wait_statuses/edit.html.erb
<h1>Editing Wait Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @wait_status %> |
<%= link_to 'Back', wait_statuses_path %>

app/views/wait_statuses/index.html.erb
<div class="index-view">
  <h1>대기자 목록</h1>

  <div class="index-commands">
    <%= link_to 'wait_statuses.csv', class:"button" do %>
      <%= fa_icon "download" %> CSV 다운로드
    <% end %>
  </div>

  <table class="index-table">
    <thead>
      <tr>
        <th>대기자</th>
        <th>테이블</th>
        <th>대기 시작 날짜</th>
        <th>전화번호</th>
        <th>이메일</th>
        <!-- <th colspan="3"></th> -->
      </tr>
    </thead>

    <tbody>
      <% @current_wait_statuses.each do |wait_status| %>
        <tr>
          <td><%= link_to wait_status.member.name, wait_status.member %></td>
          <td><%= wait_status.table_type.capitalize %></td>
          <td><%= wait_status.start_date %></td>
          <td><%= wait_status.member.phone %></td>
          <td><%= wait_status.member.email %></td>
          <!--
          <td><%#= link_to 'Show', wait_status %></td>
          <td><%#= link_to 'Edit', edit_wait_status_path(wait_status) %></td>
          <td><%#= link_to 'Destroy', wait_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          -->
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/wait_statuses/new.html.erb
<h1><%= @member.name %>님을 위한 등록 예약 신청	</h1>


<%= render 'form' %>

app/views/wait_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Table type:</strong>
  <%= @wait_status.table_type %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @wait_status.start_date %>
</p>

<p>
  <strong>Member:</strong>
  <%= @wait_status.member_id %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @wait_status.employee_id %>
</p>

<%= link_to 'Edit', edit_wait_status_path(@wait_status) %> |
<%= link_to 'Back', wait_statuses_path %>