config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :members
  resources :employees
  resources :wait_statuses
  resources :registrations, except: :show
  resources :sessions, except: :index

  # Set the root url
  root :to => 'home#home', as: :home

  # Authentication
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

end

app/models/member.rb
class Member < ActiveRecord::Base

	GENDERS = [['남', :male],['여', :female],['Other', :other]]
		
	scope :alphabetical, -> { order('name') }
	scope :birthday_today, -> { where("cast(strftime('%m', birthdate) as int) = ? AND cast(strftime('%d', birthdate) as int) = ?", Date.today.month, Date.today.day) }

	validates_presence_of :name, :phone, :gender, :join_date, :birthdate, :school

	def self.search(search)
	  where("name LIKE ?", "%#{search}%") 
	end

	def status
		ws = WaitStatus.for_member(self.id).current.first
		return ws unless ws.nil?
		reg = Registration.for_member(self.id).current.first
		return reg unless reg.nil?
		nil
	end

	def status_string
		if self.status.class.name == "Registration"
      return "#{self.status.seat_number}번 테이블 ~#{self.status.end_date}"
    elsif self.status.class.name == "WaitStatus"
      return "#{self.status.table_type.capitalize} 테이블 #{self.status.start_date}부터 대기 중"
    else 
      return "없음"
    end
	end

	def employee
		Employee.find(self.employee_id)
	end

	def self.to_csv

    CSV.generate do |csv|
      csv << column_names + ['Status']
      all.each do |result|
        csv << result.attributes.values_at(*column_names - ['Status']) + [result.status_string]
      end
    end
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :check_login
  authorize_resource

  # GET /members
  # GET /members.json
  def index
    if params[:search]
      @members = Member.search(params[:search]).alphabetical
    else
      @members = Member.all.alphabetical
    end
    respond_to do |format|
      format.html
      format.csv { send_data @members.to_csv }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @employee = Employee.find(@member.employee_id)
    @registrations = Registration.for_member(@member.id)
    @wait_statuses = WaitStatus.for_member(@member.id)
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)
    @member.join_date = Date.today
    @member.employee_id = current_user.id
    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :phone, :email, :gender, :join_date, :birthdate, :employee_id, :school, :comment)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= @member.errors.count %>개 문제가 있었습니다:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :name, placeholder: "이름" %>
    <%= f.text_field :phone, placeholder: "전화번호" %>
    <%= f.text_field :email, placeholder: "이메일" %>
    <%= f.text_field :school, placeholder: "학교" %>
    <%= f.select :gender, collection: Member::GENDERS %>
    <br><%= f.label "생년월일" %><br>
    <%= f.date_select :birthdate, :start_year=>1900,:end_year=>Date.current.year, :selected=>1990 %>
    <%= f.label "특이사항" %><br>
    <%= f.text_area :comment, placeholder: "" %>
    <%= f.submit "회원 저장", class:"button" %>
  </div>
<% end %>

app/views/members/_member_registrations.html.erb
<div class="box">
	<h3>회원 가입 내역</h3>

	<table class="index-table">
		<thead>
			<tr>
				<th>좌석 번호</th>
				<th>등록 날짜</th>
				<th>등록 마감 날짜</th>
				<th>등록 담당 직원</th>
				<th></th>
			</tr>
		</thead>
		<% @registrations.each do |r| %>
			<% employee = Employee.find(r.employee_id)%>
			<tr>
				<td><%= r.seat_number %></td>
				<td><%= r.start_date %></td>
				<td><%= r.end_date %></td>
				<td><%= link_to employee.name, employee %></td>
				<td><%= link_to '등록 수정하기', edit_registration_path(r) %></td>
			</tr>
		<% end %>
	</table>
</div>

app/views/members/_member_wait_statuses.html.erb
<div class="box">
	<h3>대기 등록 내역</h3>

	<table class="index-table">
		<thead>
			<tr>
				<th>테이블 타입</th>
				<th>대기 시작 날짜</th>
				<th>대기 마감 날짜</th>
				<th>대기 담당 직원</th>
			</tr>
		</thead>
		<% @wait_statuses.each do |ws| %>
			<% employee = Employee.find(ws.employee_id)%>
			<tr>
				<td><%= ws.table_type %></td>
				<td><%= ws.start_date %></td>
				<td><%= ws.end_date %></td>
				<td><%= link_to employee.name, employee %></td>
			</tr>
		<% end %>
	</table>
</div>

app/views/members/edit.html.erb
<h1>회원 정보 수정</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<div class="index-view">
  <h1>회원 목록</h1>
  <div class="index-commands">
    <%= link_to new_member_path, class:"button" do %>
      <%= fa_icon "plus" %> 회원추가
    <% end %>
    <%= link_to 'members.csv', class:"button" do %>
      <%= fa_icon "download" %> CSV 다운로드
    <% end %>
    <%= form_tag(members_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "회원 검색" %>
    <% end %>
  </div>

  <table class="index-table">
    <thead>
      <tr>
        <th>성함</th>
        <th>전화번호</th>
        <th>성별</th>
        <th>가입 날짜</th>
        <th colspan="2">가입 상태</th>
      </tr>
    </thead>

    <tbody>
      <% @members.each do |member| %>
        <tr>
          <td><%= link_to member.name, member %></td>
          <td><%= member.phone %></td>
          <td><%= member.gender.capitalize %></td>
          <td><%= member.join_date %></td>
          <td colspan="2">
            <%= member.status_string %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/members/new.html.erb
<h1>회원 추가</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<div class="sidebar width-40" >

  <div>
    <h1><%= @member.name %></h1>
    <%= link_to '+ 대기 등록 신청', new_wait_status_path(:member_id => @member.id), class:"button" %>
    <%= link_to '+ 테이블 등록 신청', new_registration_path(:member_id => @member.id), class:"button" %>
  </div>

  <p>
    <strong>전화번호:</strong>
    <%= @member.phone %>
  </p>

  <p>
    <strong>이메일:</strong>
    <%= @member.email %>
  </p>

  <p>
    <strong>성별:</strong>
    <%= @member.gender %>
  </p>

  <p>
    <strong>가입 날짜:</strong>
    <%= @member.join_date %>
  </p>

  <p>
    <strong>생년월일:</strong>
    <%= @member.birthdate %>
  </p>

  <p>
    <strong>학교:</strong>
    <%= @member.school %>
  </p>

  <p>
    <strong>가입 담당 직원:</strong>
    <%= @employee.name %>
  </p>

  <p>
    <strong>특이사항:</strong>
    <%= @member.comment %>
  </p>
  <%= link_to '회원 정보 수정하기', edit_member_path(@member) %>
</div>

<div class="sidebar right-sidebar width-50">
  <%= render 'member_registrations' %>
  <%= render 'member_wait_statuses' %>
</div>